services:
  terraform:
    build: .
    volumes:
      - .:/app
      - ~/.aws:/root/.aws
      - ~/.config/gcloud:/root/.config/gcloud
    tty: true
    entrypoint: /bin/bash
  aws:
    image: amazon/aws-cli
    volumes:
      - ~/.aws:/root/.aws
    tty: true
    entrypoint: /bin/bash
  gcloud:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    tty: true
